### ISSUE TITLE
Laravel 5.* support?

### ISSUE THREAD

**Issue by botelho** [maxhoffmann/parsedown-laravel#1]
Any plans for L5.\* support?

**Comment by maxhoffmann** [comment]
Haven’t had a look into the Laravel 5 changes. I’d be very thankful for pull requests. :)

**Comment by FNFR** [comment]
ll' it work on L5? 

OBS.: I am new here, what is a Pull Request?

**Comment by maxhoffmann** [comment]
Hello @FNFR! GitHub has a nice page about explaining what a pull request is: https://help.github.com/articles/using-pull-requests. Hope to see your first one soon! :)

To answer your question: I don’t know if this works with L5 because I have never used this version. Feel free to try it out and let me know if it does/does not.

**Comment by smallst** [comment]
works with laravel 5

**Comment by maxhoffmann** [comment]
Thanks for answering @smallst! Closing this now.
